# Generated by Django 2.0.2 on 2018-02-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='meter title')),
                ('directory', models.CharField(max_length=255, verbose_name='output file directory')),
            ],
            options={
                'verbose_name': 'heat meter',
                'verbose_name_plural': 'heat meters',
                'ordering': ['-title'],
            },
        ),
    ]
