# Generated by Django 2.0.2 on 2018-02-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('value', models.PositiveIntegerField(verbose_name='counter value')),
                ('delta_from_previous', models.PositiveIntegerField(verbose_name='delta')),
            ],
            options={
                'verbose_name': 'heat meter reading',
            },
        ),
        migrations.CreateModel(
            name='SyncFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='file name')),
                ('hash', models.CharField(blank=True, default=None, help_text='file hash in MD5 format', max_length=32, null=True, verbose_name='file hash')),
                ('rowcount', models.PositiveIntegerField(default=0, verbose_name='row count')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='started')),
                ('finished', models.DateTimeField(blank=True, default=None, null=True, verbose_name='ended')),
                ('status', models.CharField(choices=[('start', 'sync started'), ('success', 'sync successfull')], default='start', max_length=10, verbose_name='status')),
            ],
            options={
                'verbose_name': 'sync log',
                'ordering': ['-started', '-finished'],
            },
        ),
        migrations.AlterField(
            model_name='meterinput',
            name='directory',
            field=models.CharField(max_length=255, unique=True, verbose_name='output file directory'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meterdata.MeterInput', verbose_name='heat meter'),
        ),
        migrations.AddField(
            model_name='syncfiles',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meterdata.MeterInput', verbose_name='sync log'),
        ),
        migrations.AddField(
            model_name='entry',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meterdata.MeterInput', verbose_name='heat meter'),
        ),
        migrations.AddField(
            model_name='entry',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meterdata.SyncFiles', verbose_name='sync log'),
        ),
        migrations.AlterUniqueTogether(
            name='syncfiles',
            unique_together={('input', 'filename', 'hash')},
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('input', 'time')},
        ),
    ]
