# Generated by Django 2.0.2 on 2018-02-21 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meterdata', '0002_auto_20180220_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncfiles',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='first seen'),
            preserve_default=False,
        ),
    ]
